[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
jackpot_smart_contract = "asADxxCjUt4JGRCwM3ohmMJ6cUgCm4DqVNTRyvo17zg"

[programs.localnet]
jackpot_smart_contract = "asADxxCjUt4JGRCwM3ohmMJ6cUgCm4DqVNTRyvo17zg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./keys/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
